add anime2020.10.json
ACGNTaiwan/Anime-List pull request #10
Opened 2020-09-01 17:05 UTC by t510599

資料來源:
- https://acgsecrets.hk/bangumi/202010/
- https://acg.gamer.com.tw/
- https://www.wikiwand.com/zh-tw/%E6%97%A5%E6%9C%AC%E5%8B%95%E7%95%AB%E5%88%97%E8%A1%A8_(2020%E5%B9%B4)

2020-09-20 15:50 UTC, james58899 requested changes
季數跑掉了

2020-09-20 15:50 UTC, james58899 commented on anime-data/anime2020.10.json
> +    "season": 1,
4沒錯吧

2020-09-20 15:50 UTC, james58899 commented on anime-data/anime2020.10.json
> +    "season": 1,
3

2020-09-20 15:50 UTC, james58899 commented on anime-data/anime2020.10.json
> +    "season": 1,
4

2020-09-20 16:42 UTC, t510599 commented
有些有其他副標的番名 如果有設 `season`
顯示時就會在後面多加上 SX
如:
`進擊的巨人 The Final Season` 會變成 `進擊的巨人 The Final Season S4`

 所以有先拔掉 還是加上去沒差(?

2020-09-20 16:54 UTC, james58899 commented
@t510599 我覺得就給他S4

2020-09-21 15:48 UTC, james58899 approved these changes

2020-09-23 11:47 UTC, merged