Add anime2021.01.json
ACGNTaiwan/Anime-List pull request #26
Opened 2020-12-19 10:10 UTC by t510599

Reference:
- https://acgsecrets.hk/bangumi/202101/
- https://twitter.com/mikan_anime_nc/status/1339980747700989953
- https://gnn.gamer.com.tw/detail.php?sn=208160
- https://acg.gamer.com.tw/
- https://gnn.gamer.com.tw/detail.php?sn=207412
- https://forum.gamer.com.tw/C.php?bsn=60037&snA=75294
- https://forum.gamer.com.tw/C.php?bsn=60037&snA=74976&page=1&gothis=1079715#1079715
- https://yuc.wiki/202101/

2020-12-19 16:36 UTC, james58899 approved these changes

2020-12-21 10:24 UTC, james58899 commented
這邊也要加一下
https://github.com/ACGNTaiwan/Anime-List/blob/879753e4270fff62d73d8d4536c0e22da4c9fc19/js/index.js#L21-L44

2020-12-21 11:48 UTC, t510599 commented
@james58899 Done.

2020-12-25 07:52 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "搖曳露營△",
原文的 SEASON2 咋不見惹 ._.

2020-12-25 07:52 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "BEASTARS",
二期？

2020-12-25 07:52 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "約定的夢幻島",
二期？

2020-12-25 07:57 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "境界觸發者",
2nd Season 不見惹 ._.

2020-12-25 08:00 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "originalName": "八十亀ちゃんかんさつにっき 八十亀ちゃんかんさつにっき 3さつめ",
是不是多了一次 `八十亀ちゃんかんさつにっき` ？

2020-12-25 08:01 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "廚神小當家",
第二期 (？

2020-12-25 08:01 UTC, Haraguroicha commented on anime-data/anime2021.01.json
> +    "name": "暗芝居",
第8期？

2020-12-25 08:03 UTC, Haraguroicha requested changes, later dismissed
註解了幾個比較有疑慮的地方，其中一個原文標題可能有誤，再麻煩確認下，感謝

2020-12-25 14:36 UTC, t510599 commented on anime-data/anime2021.01.json
> +    "originalName": "八十亀ちゃんかんさつにっき 八十亀ちゃんかんさつにっき 3さつめ",
對 謝謝提醒

2020-12-25 14:43 UTC, t510599 commented on anime-data/anime2021.01.json
> +    "originalName": "八十亀ちゃんかんさつにっき 八十亀ちゃんかんさつにっき 3さつめ",
Fixed in commit d16e9c4.

2021-01-01 10:08 UTC, merged