Add anime2021.04.json
ACGNTaiwan/Anime-List pull request #30
Opened 2021-03-14 16:45 UTC by t510599

Reference:
- https://acgsecrets.hk/bangumi/202104/
- https://acg.gamer.com.tw/
- https://home.gamer.com.tw/creationDetail.php?sn=5088434

2021-03-14 17:05 UTC, Haraguroicha requested changes
標點符號問題而已，剩下的東西可能先拿掉讓他合一版之後再開追加資訊的 PR 吧？
@james58899 意見如何？

2021-03-14 17:05 UTC, Haraguroicha commented on anime-data/anime2021.04.json
> +    "description": "Nierland”是一個人工智慧綜合主題公園，夢想，希望和科學融為一體。作為歷史上第一個自律學習型 AI，Vivy 一直是該設施的 AI 演員，每天站在舞台上唱歌。但是，它的受歡迎程度還不夠。讓每個人都對歌曲感到滿意。Vivy繼續唱歌，目標是全心全意地唱一首歌，站在公園的主要舞台上，以完成自己的使命。有一天，一個名為マツモト的 AI 出現在Vivy身邊。マ
`Nierland”` -> `”Nierland”` ?

2021-03-15 04:37 UTC, james58899 commented
@Haraguroicha 還要加進 `js/index.js`

2021-03-15 04:39 UTC, Haraguroicha commented
> @Haraguroicha @t510599 還要加進 `js/index.js`

我其實有在想，要不要讓他自動產生就不用手動加了...

2021-03-15 04:39 UTC, Haraguroicha approved these changes

2021-03-15 04:41 UTC, gnehs commented
> > @Haraguroicha @t510599 還要加進 `js/index.js`
> 
> 我其實有在想，要不要讓他自動產生就不用手動加了...

可是我讓他要手動加的目的是讓他不要顯示還沒做好的資料

2021-03-15 04:43 UTC, Haraguroicha commented
> > > @Haraguroicha @t510599 還要加進 `js/index.js`
> > 
> > 
> > 我其實有在想，要不要讓他自動產生就不用手動加了...
> 
> 可是我讓他要手動加的目的是讓他不要顯示還沒做好的資料

但是現在都要 PR accepted 之後才會出來了，有差嗎 ._. ？

2021-03-15 04:43 UTC, james58899 commented
顯示不完整的資料感覺比沒資料好，讓他全部都顯示吧

2021-03-16 12:22 UTC, james58899 approved these changes

2021-03-16 12:26 UTC, james58899 commented
🚀

2021-03-16 12:26 UTC, merged