[Add] anime2021.07.json
ACGNTaiwan/Anime-List pull request #34
Opened 2021-06-25 16:18 UTC by t510599

Reference:
- https://acgsecrets.hk/bangumi/202107/
- https://home.gamer.com.tw/creationDetail.php?sn=5176766
- https://www.facebook.com/animategamer/posts/4214758878586451
- https://www.wikiwand.com/zh-tw/%E8%93%8B%E7%89%B9%E6%A9%9F%E5%99%A8%E4%BA%BAARC

2021-06-25 16:19 UTC, t510599 commented
順便更新了 `acgsecrets` 的爬蟲

2021-06-25 18:14 UTC, Haraguroicha requested changes
兩個地方麻煩幫確認一下，感謝

2021-06-25 18:14 UTC, Haraguroicha commented on anime-data/anime2021.07.json
> +    "season": 1,
wiki 說他應該是 s3

2021-06-25 18:14 UTC, Haraguroicha commented on anime-data/anime2021.07.json
> +    "date": "7/1",
他 6/25 偷跑了兩集，所以真的還是 7/1 嗎xDDD？

2021-06-26 04:12 UTC, t510599 commented on anime-data/anime2021.07.json
> +    "date": "7/1",
https://www.facebook.com/animategamer/posts/4211551012240571
巴哈先行放送不能算吧 XD
我個人以官方 TV 時間為主 不知道其他人怎麼看

2021-06-26 04:13 UTC, t510599 commented on anime-data/anime2021.07.json
> +    "season": 1,
不確定他會像是外傳還是接續劇情，所以就先填了 S1 (?
順便問一下遇到這種問題該怎麼算季度

2021-06-26 05:48 UTC, Haraguroicha commented on anime-data/anime2021.07.json
> +    "date": "7/1",
好噢，這類例外可能不多，不理他🤣

2021-06-26 05:56 UTC, Haraguroicha commented on anime-data/anime2021.07.json
> +    "season": 1,
看起來他是放新篇啦，反正遇到就是都先 mark 起來，等放送確定之後回頭修就好👌

2021-06-26 05:57 UTC, Haraguroicha approved these changes

2021-06-26 05:58 UTC, merged